### ISSUE TITLE
Not Responsive

### ISSUE THREAD

**Issue by sokocha** [mateuszdw/qaror#4]
Great application Mateus. I've cloned it and customised it to my likings.

When I manually adjust the browser, it appears to be responsive. However, when I view it on a  mobile device, it shows the ordinary desktop version. 

I thought maybe it had to do with the viewport not being set. So I included the following meta tag:
<meta name="viewport" content="width=device-width, initial-scale=1">

However, it did not work and it didn't satisfy Google's "Mobile-Friendly" Test.
http://www.google.com/webmasters/tools/mobile-friendly/?url=qaror.herokuapp.com

Is it an issue with the Rails version or some of the gems?

**Comment by mateuszdw** [comment]
Hello Sokocha,

right, it looks like responsive but its not fully tested. Project not use any responsive columns right now. I bet its an issue with some html tags in head section. I have limited time for this project but will try return to this issue for a few days.

**Comment by mateuszdw** [comment]
I get into it earlier and yes that was head section bc5e4664c615f5034ab21259afdd2ff39afd24ef. I know current mobile version for this project is not look nice :/ Maybe we will fix it in the future.

**Comment by sokocha** [comment]
Okay. Thanks. What is wrong with the head? I want to fix it on my version of the app.

Sadiq Okocha
B.S. Petroleum Engineering, 2011
The University of Texas at Austin

**Comment by mateuszdw** [comment]
You can see changes in latest commit -> bc5e4664c615f5034ab21259afdd2ff39afd24ef
You must paste this:
```<meta name="viewport" content="width=device-width, initial-scale=1">```
in your head section, in app/views/layouts/application.html.erb file.

**Comment by sokocha** [comment]
Yes I've done this long ago, but still not responsive  on mobile for some reason. My site is www.legal9ja.com and the source code is https://github.com/sokocha/LegalEagle. I've only changed to the bootstrap navbar and other minor styling choices. If you see my application.html.erb I've included the meta tag. This makes me think it's something with this version of rails. Or do you notice anything I may have done incorrectly?

Sadiq Okocha
B.S. Petroleum Engineering, 2011
The University of Texas at Austin

**Comment by mateuszdw** [comment]
It looks like you not pushed your changes on server host :) Besiade that, you should paste this line outside of the condition: ```<% if controller_name == 'main' %>```
Good place for viewport line will be after ```<meta name="author" content="legal9ja" />```

**Comment by sokocha** [comment]
Ahh! That does the trick! It was INSIDE of the if condition. Thanks so much
Meteusz.

I really appreciate your awesome support!

Kind Regards

On Fri, Jul 31, 2015 at 1:03 PM, Mateusz Dw <notifications@github.com>
wrote:

> It looks like you not pushed your changes on server host :) Besiade that,
> you should paste this line outside of the condition: <% if
> controller_name == 'main' %>
> Good place for viewport line will be after <meta name="author"
> content="legal9ja" />
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mateuszdw/qaror/issues/4#issuecomment-126669295>.
>



-- 
Sadiq Sani Okocha
B.S. Petroleum Engineering, 2011
The University of Texas at Austin

MSc. Engineering Management (Distinction), 2015
The University of York

**Comment by mateuszdw** [comment]
I'm glad I could help :)
